### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by rukisuli** [automate-community/automate-flow-compiler#1]
Hello,

I stumbled upon this project a few weeks ago while googling an Automate question. I had actually tried to do something similar and had partially reverse engineered the .flo files. I'm curious what the status of this project is cause I would love to see something like this fully realized. I'm not sure how you are approaching this, but let me know if you are interested in any of my findings.

**Comment by tory1103** [comment]
Hello, this project is actually unmaintained but there is a community in WhatsApp where you can find any help with .flo reverse engineering... feel free to reopen this issue if you have any doubt.
